starforged:
  ruleset: starforged
  source:
    authors:
      - name: Shawn Tomkin
    url: https://ironswornrpg.com
    title: "Ironsworn: Starforged Rulebook"
    license: https://creativecommons.org/licenses/by/4.0
    date: 2022-05-06
  oracles:
    derelicts:
      extends: starforged/collections/oracles/derelicts
      name: Derelicts
      collections:
        production:
          name: Production
          _source:
            page: 358
          contents:
            area:
              name: Area
              table:
                - low: 1
                  high: 8
                  result: Airlock or staging area
                - low: 9
                  high: 16
                  result: Assembly or processing
                - low: 17
                  high: 24
                  result: Cargo bay
                - low: 25
                  high: 32
                  result: Equipment storage
                - low: 33
                  high: 40
                  result: Exosuit bay
                - low: 41
                  high: 48
                  result: Harvesting or mining platform
                - low: 49
                  high: 56
                  result: Monitoring or control room
                - low: 57
                  high: 64
                  result: Processed goods storage
                - low: 65
                  high: 72
                  result: Raw materials storage
                - low: 73
                  high: 80
                  result: Scrapyard
                - low: 81
                  high: 85
                  result: *result:NewZone
                - low: 86
                  high: 100
                  result: *result:NewZoneViaAccess
            feature:
              name: Feature
              table:
                - low: 1
                  high: 8
                  result: Cargo lifts
                - low: 9
                  high: 16
                  result: Control panels
                - low: 17
                  high: 24
                  result: Disassembled machinery
                - low: 25
                  high: 32
                  result: Elevated walkways
                - low: 33
                  high: 40
                  result: Environment suits
                - low: 41
                  high: 48
                  result: Ill-fated workers
                - low: 49
                  high: 56
                  result: Immense machinery
                - low: 57
                  high: 64
                  result: Sealed or locked containers
                - low: 65
                  high: 72
                  result: Tools
                - low: 73
                  high: 80
                  result: Vats of chemicals or gas
                - low: 81
                  high: 88
                  result: Written manifest
                - low: 89
                  high: 100
                  result: *result:Descriptor+Focus
            peril:
              name: Peril
              table:
                - low: 1
                  high: 10
                  result: Claustrophobic spaces
                - low: 11
                  high: 20
                  result: Dangerous machinery
                - low: 21
                  high: 30
                  result: Disturbing evidence of exploited labor
                - low: 31
                  high: 40
                  result: Extreme temperatures
                - low: 41
                  high: 50
                  result: Hazardous materials
                - low: 51
                  high: 60
                  result: Impending industrial disaster
                - low: 61
                  high: 70
                  result: Malfunctioning automation
                - low: 71
                  high: 80
                  result: Rivals seek to secure these resources
                - low: 81
                  high: 90
                  result: Signs of an unearthed or manufactured threat
                - low: 91
                  high: 98
                  result: *result:Action+Theme
                - low: 99
                  high: 100
                  result: *result:RollTwice
            opportunity:
              name: Opportunity
              table:
                - low: 1
                  high: 20
                  result: Helpful vehicle or transport
                - low: 21
                  high: 40
                  result: Rare or valuable resource
                - low: 41
                  high: 60
                  result: Salvageable materials
                - low: 61
                  high: 80
                  result: Useful equipment
                - low: 81
                  high: 100
                  result: Valuable cargo
