source:
  authors:
		- Shawn Tomkin
  title: "Ironsworn: Starforged Rulebook"
  license: https://creativecommons.org/licenses/by/4.0
collections:
  derelicts:
    title:
      canonical: Derelicts
    _source:
      date: 2022-05-06
    collections:
      production:
        name: Production

        _source:
          page: 358
        contents:
          area:
            name: Area
            table:
                - result: Airlock or staging area
                - result: Assembly or processing
                - result: Cargo bay
                - result: Equipment storage
                - result: Exosuit bay
                - result: Harvesting or mining platform
                - result: Monitoring or control room
                - result: Processed goods storage
                - result: Raw materials storage
                - result: Scrapyard
                - result: *result:NewZone
                - result: *result:NewZoneViaAccess
          feature:
            name: Feature
            table:
                - result: Cargo lifts
                - result: Control panels
                - result: Disassembled machinery
                - result: Elevated walkways
                - result: Environment suits
                - result: Ill-fated workers
                - result: Immense machinery
                - result: Sealed or locked containers
                - result: Tools
                - result: Vats of chemicals or gas
                - result: Written manifest
                - result: *result:Descriptor+Focus
          peril:
            name: Peril
            table:
                - result: Claustrophobic spaces
                - result: Dangerous machinery
                - result: Disturbing evidence of exploited labor
                - result: Extreme temperatures
                - result: Hazardous materials
                - result: Impending industrial disaster
                - result: Malfunctioning automation
                - result: Rivals seek to secure these resources
                - result: Signs of an unearthed or manufactured threat
                - result: *result:Action+Theme
                - result: *result:RollTwice
          opportunity:
            name: Opportunity
            table:
                - result: Helpful vehicle or transport
                - result: Rare or valuable resource
                - result: Salvageable materials
                - result: Useful equipment
                - result: Valuable cargo
